name: tutor-virtual

variables: 
  TUTOR_API_URL: "https://"
  //falta regenar la url con la final//
  USE_MOCK: "False"  

dependencies:
  -python=3.10
  -pip
  -pip:
      -streamlit
      -requests
      -reportlab
