name: tutor-virtual

variables: 
  TUTOR_API_URL: "https://"
  USE_MOCK: "False"  

dependencies:
  -python=3.10
  -pip
  -pip:
      -streamlit
      -requests
      -reportlab
      -pandas
      -numpy
      -matplotlib
      -